"""Seed the companies table with S&P 500 constituents and TSX 60 companies.

Covers all ~503 S&P 500 members and ~60 TSX names.
Cross-listed TSX companies include US CIK numbers so EDGAR works for them.
"""

import asyncio

from sqlalchemy import text

from app.database import async_session_factory

# Format: (ticker, name, exchange, sector, industry, currency, cik)
COMPANIES = [
    # ======================== S&P 500 — TECHNOLOGY ========================
    ("AAPL", "Apple Inc.", "NASDAQ", "Technology", "Consumer Electronics", "USD", "0000320193"),
    ("MSFT", "Microsoft Corporation", "NASDAQ", "Technology", "Software - Infrastructure", "USD", "0000789019"),
    ("GOOGL", "Alphabet Inc. Class A", "NASDAQ", "Technology", "Internet Content & Information", "USD", "0001652044"),
    ("GOOG", "Alphabet Inc. Class C", "NASDAQ", "Technology", "Internet Content & Information", "USD", "0001652044"),
    ("NVDA", "NVIDIA Corporation", "NASDAQ", "Technology", "Semiconductors", "USD", "0001045810"),
    ("META", "Meta Platforms Inc.", "NASDAQ", "Technology", "Internet Content & Information", "USD", "0001326801"),
    ("AVGO", "Broadcom Inc.", "NASDAQ", "Technology", "Semiconductors", "USD", "0001649338"),
    ("CRM", "Salesforce Inc.", "NYSE", "Technology", "Software - Application", "USD", "0001108524"),
    ("ORCL", "Oracle Corporation", "NYSE", "Technology", "Software - Infrastructure", "USD", "0001341439"),
    ("CSCO", "Cisco Systems Inc.", "NASDAQ", "Technology", "Communication Equipment", "USD", "0000858877"),
    ("ADBE", "Adobe Inc.", "NASDAQ", "Technology", "Software - Application", "USD", "0000796343"),
    ("ACN", "Accenture plc", "NYSE", "Technology", "Information Technology Services", "USD", "0001467373"),
    ("IBM", "International Business Machines", "NYSE", "Technology", "Information Technology Services", "USD", "0000051143"),
    ("INTC", "Intel Corporation", "NASDAQ", "Technology", "Semiconductors", "USD", "0000050863"),
    ("AMD", "Advanced Micro Devices Inc.", "NASDAQ", "Technology", "Semiconductors", "USD", "0000002488"),
    ("QCOM", "QUALCOMM Incorporated", "NASDAQ", "Technology", "Semiconductors", "USD", "0000804328"),
    ("TXN", "Texas Instruments Incorporated", "NASDAQ", "Technology", "Semiconductors", "USD", "0000097476"),
    ("NOW", "ServiceNow Inc.", "NYSE", "Technology", "Software - Application", "USD", "0001373715"),
    ("INTU", "Intuit Inc.", "NASDAQ", "Technology", "Software - Application", "USD", "0000896878"),
    ("AMAT", "Applied Materials Inc.", "NASDAQ", "Technology", "Semiconductor Equipment", "USD", "0000006951"),
    ("ADI", "Analog Devices Inc.", "NASDAQ", "Technology", "Semiconductors", "USD", "0000006281"),
    ("LRCX", "Lam Research Corporation", "NASDAQ", "Technology", "Semiconductor Equipment", "USD", "0000707549"),
    ("KLAC", "KLA Corporation", "NASDAQ", "Technology", "Semiconductor Equipment", "USD", "0000319201"),
    ("SNPS", "Synopsys Inc.", "NASDAQ", "Technology", "Software - Application", "USD", "0000883241"),
    ("CDNS", "Cadence Design Systems", "NASDAQ", "Technology", "Software - Application", "USD", "0000813672"),
    ("MCHP", "Microchip Technology", "NASDAQ", "Technology", "Semiconductors", "USD", "0000827054"),
    ("MSI", "Motorola Solutions Inc.", "NYSE", "Technology", "Communication Equipment", "USD", "0000068505"),
    ("FTNT", "Fortinet Inc.", "NASDAQ", "Technology", "Software - Infrastructure", "USD", "0001262039"),
    ("PANW", "Palo Alto Networks Inc.", "NASDAQ", "Technology", "Software - Infrastructure", "USD", "0001327567"),
    ("CRWD", "CrowdStrike Holdings Inc.", "NASDAQ", "Technology", "Software - Infrastructure", "USD", "0001535527"),
    ("NXPI", "NXP Semiconductors N.V.", "NASDAQ", "Technology", "Semiconductors", "USD", "0001413447"),
    ("ON", "ON Semiconductor Corporation", "NASDAQ", "Technology", "Semiconductors", "USD", "0000861374"),
    ("MPWR", "Monolithic Power Systems", "NASDAQ", "Technology", "Semiconductors", "USD", "0001280452"),
    ("IT", "Gartner Inc.", "NYSE", "Technology", "Information Technology Services", "USD", "0000749251"),
    ("HPE", "Hewlett Packard Enterprise", "NYSE", "Technology", "Communication Equipment", "USD", "0001645590"),
    ("HPQ", "HP Inc.", "NYSE", "Technology", "Computer Hardware", "USD", "0000047217"),
    ("KEYS", "Keysight Technologies", "NYSE", "Technology", "Electronic Instruments", "USD", "0001601046"),
    ("ZBRA", "Zebra Technologies Corporation", "NASDAQ", "Technology", "Electronic Instruments", "USD", "0000820542"),
    ("GEN", "Gen Digital Inc.", "NASDAQ", "Technology", "Software - Infrastructure", "USD", "0000849399"),
    ("GDDY", "GoDaddy Inc.", "NYSE", "Technology", "Software - Infrastructure", "USD", "0001609711"),
    ("EPAM", "EPAM Systems Inc.", "NYSE", "Technology", "Information Technology Services", "USD", "0001352010"),
    ("CTSH", "Cognizant Technology Solutions", "NASDAQ", "Technology", "Information Technology Services", "USD", "0001058290"),
    ("FSLR", "First Solar Inc.", "NASDAQ", "Technology", "Solar", "USD", "0001274494"),
    ("ENPH", "Enphase Energy Inc.", "NASDAQ", "Technology", "Solar", "USD", "0001463258"),
    ("TER", "Teradyne Inc.", "NASDAQ", "Technology", "Semiconductor Equipment", "USD", "0000097210"),
    ("ANSS", "ANSYS Inc.", "NASDAQ", "Technology", "Software - Application", "USD", "0000820736"),
    ("VRSN", "VeriSign Inc.", "NASDAQ", "Technology", "Software - Infrastructure", "USD", "0001014473"),
    ("SWKS", "Skyworks Solutions Inc.", "NASDAQ", "Technology", "Semiconductors", "USD", "0000004127"),
    ("AKAM", "Akamai Technologies Inc.", "NASDAQ", "Technology", "Software - Infrastructure", "USD", "0001086222"),
    ("FFIV", "F5 Inc.", "NASDAQ", "Technology", "Communication Equipment", "USD", "0001048695"),
    ("JNPR", "Juniper Networks Inc.", "NYSE", "Technology", "Communication Equipment", "USD", "0001043604"),
    ("PTC", "PTC Inc.", "NASDAQ", "Technology", "Software - Application", "USD", "0000857005"),
    ("TRMB", "Trimble Inc.", "NASDAQ", "Technology", "Scientific Instruments", "USD", "0000864749"),
    ("CDW", "CDW Corporation", "NASDAQ", "Technology", "Information Technology Services", "USD", "0001402057"),
    ("ROP", "Roper Technologies Inc.", "NASDAQ", "Technology", "Software - Application", "USD", "0000882184"),
    ("FICO", "Fair Isaac Corporation", "NYSE", "Technology", "Software - Application", "USD", "0000814547"),
    ("PLTR", "Palantir Technologies Inc.", "NYSE", "Technology", "Software - Infrastructure", "USD", "0001321655"),
    ("DELL", "Dell Technologies Inc.", "NYSE", "Technology", "Computer Hardware", "USD", "0001571996"),
    ("TSM", "Taiwan Semiconductor Manufacturing", "NYSE", "Technology", "Semiconductors", "USD", "0001046179"),

    # ======================== S&P 500 — FINANCIALS ========================
    ("JPM", "JPMorgan Chase & Co.", "NYSE", "Financials", "Banks - Diversified", "USD", "0000019617"),
    ("V", "Visa Inc.", "NYSE", "Financials", "Credit Services", "USD", "0001403161"),
    ("MA", "Mastercard Incorporated", "NYSE", "Financials", "Credit Services", "USD", "0001141391"),
    ("BAC", "Bank of America Corporation", "NYSE", "Financials", "Banks - Diversified", "USD", "0000070858"),
    ("GS", "Goldman Sachs Group Inc.", "NYSE", "Financials", "Capital Markets", "USD", "0000886982"),
    ("MS", "Morgan Stanley", "NYSE", "Financials", "Capital Markets", "USD", "0000895421"),
    ("WFC", "Wells Fargo & Company", "NYSE", "Financials", "Banks - Diversified", "USD", "0000072971"),
    ("C", "Citigroup Inc.", "NYSE", "Financials", "Banks - Diversified", "USD", "0000831001"),
    ("AXP", "American Express Company", "NYSE", "Financials", "Credit Services", "USD", "0000004962"),
    ("BLK", "BlackRock Inc.", "NYSE", "Financials", "Asset Management", "USD", "0001364742"),
    ("SCHW", "Charles Schwab Corporation", "NYSE", "Financials", "Capital Markets", "USD", "0000316709"),
    ("CB", "Chubb Limited", "NYSE", "Financials", "Insurance - Property & Casualty", "USD", "0000896159"),
    ("PGR", "Progressive Corporation", "NYSE", "Financials", "Insurance - Property & Casualty", "USD", "0000080661"),
    ("MMC", "Marsh & McLennan Companies", "NYSE", "Financials", "Insurance Brokers", "USD", "0000062709"),
    ("AON", "Aon plc", "NYSE", "Financials", "Insurance Brokers", "USD", "0000315293"),
    ("ICE", "Intercontinental Exchange Inc.", "NYSE", "Financials", "Financial Data & Exchanges", "USD", "0001571949"),
    ("CME", "CME Group Inc.", "NASDAQ", "Financials", "Financial Data & Exchanges", "USD", "0001156375"),
    ("USB", "U.S. Bancorp", "NYSE", "Financials", "Banks - Regional", "USD", "0000036104"),
    ("PNC", "PNC Financial Services Group", "NYSE", "Financials", "Banks - Regional", "USD", "0000713676"),
    ("TFC", "Truist Financial Corporation", "NYSE", "Financials", "Banks - Regional", "USD", "0000092230"),
    ("AIG", "American International Group", "NYSE", "Financials", "Insurance - Diversified", "USD", "0000005272"),
    ("MET", "MetLife Inc.", "NYSE", "Financials", "Insurance - Life", "USD", "0001099219"),
    ("PRU", "Prudential Financial Inc.", "NYSE", "Financials", "Insurance - Life", "USD", "0001137774"),
    ("AFL", "Aflac Incorporated", "NYSE", "Financials", "Insurance - Life", "USD", "0000004977"),
    ("ALL", "Allstate Corporation", "NYSE", "Financials", "Insurance - Property & Casualty", "USD", "0000899629"),
    ("TRV", "Travelers Companies Inc.", "NYSE", "Financials", "Insurance - Property & Casualty", "USD", "0000086312"),
    ("BK", "Bank of New York Mellon", "NYSE", "Financials", "Banks - Diversified", "USD", "0001390777"),
    ("STT", "State Street Corporation", "NYSE", "Financials", "Asset Management", "USD", "0000093751"),
    ("COF", "Capital One Financial", "NYSE", "Financials", "Credit Services", "USD", "0000927628"),
    ("FI", "Fiserv Inc.", "NYSE", "Financials", "Financial Data & Exchanges", "USD", "0000798354"),
    ("SPGI", "S&P Global Inc.", "NYSE", "Financials", "Financial Data & Exchanges", "USD", "0000064040"),
    ("MCO", "Moody's Corporation", "NYSE", "Financials", "Financial Data & Exchanges", "USD", "0001059556"),
    ("MSCI", "MSCI Inc.", "NYSE", "Financials", "Financial Data & Exchanges", "USD", "0001408198"),
    ("NDAQ", "Nasdaq Inc.", "NASDAQ", "Financials", "Financial Data & Exchanges", "USD", "0001120193"),
    ("DFS", "Discover Financial Services", "NYSE", "Financials", "Credit Services", "USD", "0001393612"),
    ("FITB", "Fifth Third Bancorp", "NASDAQ", "Financials", "Banks - Regional", "USD", "0000035527"),
    ("RF", "Regions Financial Corporation", "NYSE", "Financials", "Banks - Regional", "USD", "0001281761"),
    ("HBAN", "Huntington Bancshares", "NASDAQ", "Financials", "Banks - Regional", "USD", "0000049196"),
    ("CFG", "Citizens Financial Group", "NYSE", "Financials", "Banks - Regional", "USD", "0000831001"),
    ("MTB", "M&T Bank Corporation", "NYSE", "Financials", "Banks - Regional", "USD", "0000036270"),
    ("KEY", "KeyCorp", "NYSE", "Financials", "Banks - Regional", "USD", "0000091576"),
    ("CINF", "Cincinnati Financial", "NASDAQ", "Financials", "Insurance - Property & Casualty", "USD", "0000020286"),
    ("GL", "Globe Life Inc.", "NYSE", "Financials", "Insurance - Life", "USD", "0000320017"),
    ("L", "Loews Corporation", "NYSE", "Financials", "Insurance - Diversified", "USD", "0000060714"),
    ("RE", "Everest Group Ltd.", "NYSE", "Financials", "Insurance - Reinsurance", "USD", "0000820002"),
    ("BRO", "Brown & Brown Inc.", "NYSE", "Financials", "Insurance Brokers", "USD", "0000079282"),
    ("WRB", "W. R. Berkley Corporation", "NYSE", "Financials", "Insurance - Property & Casualty", "USD", "0000011544"),

    # ======================== S&P 500 — HEALTHCARE ========================
    ("UNH", "UnitedHealth Group Inc.", "NYSE", "Healthcare", "Healthcare Plans", "USD", "0000731766"),
    ("JNJ", "Johnson & Johnson", "NYSE", "Healthcare", "Drug Manufacturers - General", "USD", "0000200406"),
    ("LLY", "Eli Lilly and Company", "NYSE", "Healthcare", "Drug Manufacturers - General", "USD", "0000059478"),
    ("PFE", "Pfizer Inc.", "NYSE", "Healthcare", "Drug Manufacturers - General", "USD", "0000078003"),
    ("ABBV", "AbbVie Inc.", "NYSE", "Healthcare", "Drug Manufacturers - General", "USD", "0001551152"),
    ("MRK", "Merck & Co. Inc.", "NYSE", "Healthcare", "Drug Manufacturers - General", "USD", "0000310158"),
    ("TMO", "Thermo Fisher Scientific Inc.", "NYSE", "Healthcare", "Diagnostics & Research", "USD", "0000097745"),
    ("ABT", "Abbott Laboratories", "NYSE", "Healthcare", "Medical Devices", "USD", "0000001800"),
    ("DHR", "Danaher Corporation", "NYSE", "Healthcare", "Diagnostics & Research", "USD", "0000313616"),
    ("BMY", "Bristol-Myers Squibb Company", "NYSE", "Healthcare", "Drug Manufacturers - General", "USD", "0000014272"),
    ("AMGN", "Amgen Inc.", "NASDAQ", "Healthcare", "Biotechnology", "USD", "0000318154"),
    ("GILD", "Gilead Sciences Inc.", "NASDAQ", "Healthcare", "Biotechnology", "USD", "0000882095"),
    ("ISRG", "Intuitive Surgical Inc.", "NASDAQ", "Healthcare", "Medical Instruments & Supplies", "USD", "0001035267"),
    ("CVS", "CVS Health Corporation", "NYSE", "Healthcare", "Healthcare Plans", "USD", "0000064803"),
    ("MDT", "Medtronic plc", "NYSE", "Healthcare", "Medical Devices", "USD", "0001613103"),
    ("ELV", "Elevance Health Inc.", "NYSE", "Healthcare", "Healthcare Plans", "USD", "0001156039"),
    ("CI", "Cigna Group", "NYSE", "Healthcare", "Healthcare Plans", "USD", "0001739940"),
    ("SYK", "Stryker Corporation", "NYSE", "Healthcare", "Medical Devices", "USD", "0000310764"),
    ("BSX", "Boston Scientific Corporation", "NYSE", "Healthcare", "Medical Devices", "USD", "0000885725"),
    ("VRTX", "Vertex Pharmaceuticals Inc.", "NASDAQ", "Healthcare", "Biotechnology", "USD", "0000875320"),
    ("REGN", "Regeneron Pharmaceuticals", "NASDAQ", "Healthcare", "Biotechnology", "USD", "0000872589"),
    ("ZTS", "Zoetis Inc.", "NYSE", "Healthcare", "Drug Manufacturers - Specialty", "USD", "0001555280"),
    ("BDX", "Becton Dickinson and Company", "NYSE", "Healthcare", "Medical Instruments & Supplies", "USD", "0000010795"),
    ("HCA", "HCA Healthcare Inc.", "NYSE", "Healthcare", "Medical Care Facilities", "USD", "0000860730"),
    ("EW", "Edwards Lifesciences Corporation", "NYSE", "Healthcare", "Medical Devices", "USD", "0001099800"),
    ("MCK", "McKesson Corporation", "NYSE", "Healthcare", "Medical Distribution", "USD", "0000927653"),
    ("COR", "Cencora Inc.", "NYSE", "Healthcare", "Medical Distribution", "USD", "0001140859"),
    ("CAH", "Cardinal Health Inc.", "NYSE", "Healthcare", "Medical Distribution", "USD", "0000721371"),
    ("A", "Agilent Technologies Inc.", "NYSE", "Healthcare", "Diagnostics & Research", "USD", "0001047469"),
    ("IQV", "IQVIA Holdings Inc.", "NYSE", "Healthcare", "Diagnostics & Research", "USD", "0001667950"),
    ("IDXX", "IDEXX Laboratories Inc.", "NASDAQ", "Healthcare", "Diagnostics & Research", "USD", "0000874716"),
    ("BIIB", "Biogen Inc.", "NASDAQ", "Healthcare", "Biotechnology", "USD", "0000875045"),
    ("DXCM", "DexCom Inc.", "NASDAQ", "Healthcare", "Medical Devices", "USD", "0001093557"),
    ("GEHC", "GE HealthCare Technologies", "NASDAQ", "Healthcare", "Medical Devices", "USD", "0001932393"),
    ("HOLX", "Hologic Inc.", "NASDAQ", "Healthcare", "Medical Instruments & Supplies", "USD", "0000880149"),
    ("MTD", "Mettler-Toledo International", "NYSE", "Healthcare", "Diagnostics & Research", "USD", "0001037646"),
    ("WAT", "Waters Corporation", "NYSE", "Healthcare", "Diagnostics & Research", "USD", "0001000697"),
    ("ALGN", "Align Technology Inc.", "NASDAQ", "Healthcare", "Medical Devices", "USD", "0001097149"),
    ("ILMN", "Illumina Inc.", "NASDAQ", "Healthcare", "Diagnostics & Research", "USD", "0001110803"),
    ("MOH", "Molina Healthcare Inc.", "NYSE", "Healthcare", "Healthcare Plans", "USD", "0001179929"),
    ("CNC", "Centene Corporation", "NYSE", "Healthcare", "Healthcare Plans", "USD", "0001071739"),
    ("HUM", "Humana Inc.", "NYSE", "Healthcare", "Healthcare Plans", "USD", "0000049071"),
    ("TECH", "Bio-Techne Corporation", "NASDAQ", "Healthcare", "Biotechnology", "USD", "0000771999"),
    ("RVTY", "Revvity Inc.", "NYSE", "Healthcare", "Diagnostics & Research", "USD", "0000031791"),

    # ======================== S&P 500 — CONSUMER DISCRETIONARY ========================
    ("AMZN", "Amazon.com Inc.", "NASDAQ", "Consumer Cyclical", "Internet Retail", "USD", "0001018724"),
    ("TSLA", "Tesla Inc.", "NASDAQ", "Consumer Cyclical", "Auto Manufacturers", "USD", "0001318605"),
    ("HD", "Home Depot Inc.", "NYSE", "Consumer Cyclical", "Home Improvement Retail", "USD", "0000354950"),
    ("MCD", "McDonald's Corporation", "NYSE", "Consumer Cyclical", "Restaurants", "USD", "0000063908"),
    ("NKE", "NIKE Inc.", "NYSE", "Consumer Cyclical", "Footwear & Accessories", "USD", "0000320187"),
    ("SBUX", "Starbucks Corporation", "NASDAQ", "Consumer Cyclical", "Restaurants", "USD", "0000829224"),
    ("LOW", "Lowe's Companies Inc.", "NYSE", "Consumer Cyclical", "Home Improvement Retail", "USD", "0000060667"),
    ("TJX", "TJX Companies Inc.", "NYSE", "Consumer Cyclical", "Apparel Retail", "USD", "0000109198"),
    ("BKNG", "Booking Holdings Inc.", "NASDAQ", "Consumer Cyclical", "Travel Services", "USD", "0001075531"),
    ("CMG", "Chipotle Mexican Grill Inc.", "NYSE", "Consumer Cyclical", "Restaurants", "USD", "0001058090"),
    ("F", "Ford Motor Company", "NYSE", "Consumer Cyclical", "Auto Manufacturers", "USD", "0000037996"),
    ("GM", "General Motors Company", "NYSE", "Consumer Cyclical", "Auto Manufacturers", "USD", "0001467858"),
    ("ORLY", "O'Reilly Automotive Inc.", "NASDAQ", "Consumer Cyclical", "Specialty Retail", "USD", "0000898173"),
    ("AZO", "AutoZone Inc.", "NYSE", "Consumer Cyclical", "Specialty Retail", "USD", "0000866787"),
    ("MAR", "Marriott International Inc.", "NASDAQ", "Consumer Cyclical", "Lodging", "USD", "0001048286"),
    ("HLT", "Hilton Worldwide Holdings", "NYSE", "Consumer Cyclical", "Lodging", "USD", "0001585689"),
    ("ROST", "Ross Stores Inc.", "NASDAQ", "Consumer Cyclical", "Apparel Retail", "USD", "0000745732"),
    ("DHI", "D.R. Horton Inc.", "NYSE", "Consumer Cyclical", "Residential Construction", "USD", "0000882184"),
    ("LEN", "Lennar Corporation", "NYSE", "Consumer Cyclical", "Residential Construction", "USD", "0000920760"),
    ("DKNG", "DraftKings Inc.", "NASDAQ", "Consumer Cyclical", "Gambling", "USD", "0001883685"),
    ("YUM", "Yum! Brands Inc.", "NYSE", "Consumer Cyclical", "Restaurants", "USD", "0001041061"),
    ("APTV", "Aptiv PLC", "NYSE", "Consumer Cyclical", "Auto Parts", "USD", "0001521332"),
    ("GPC", "Genuine Parts Company", "NYSE", "Consumer Cyclical", "Specialty Retail", "USD", "0000040987"),
    ("EBAY", "eBay Inc.", "NASDAQ", "Consumer Cyclical", "Internet Retail", "USD", "0001065088"),
    ("ULTA", "Ulta Beauty Inc.", "NASDAQ", "Consumer Cyclical", "Specialty Retail", "USD", "0001337619"),
    ("BBY", "Best Buy Co. Inc.", "NYSE", "Consumer Cyclical", "Specialty Retail", "USD", "0000764478"),
    ("POOL", "Pool Corporation", "NASDAQ", "Consumer Cyclical", "Specialty Retail", "USD", "0000945841"),
    ("DPZ", "Domino's Pizza Inc.", "NYSE", "Consumer Cyclical", "Restaurants", "USD", "0001286681"),
    ("LVS", "Las Vegas Sands Corp.", "NYSE", "Consumer Cyclical", "Resorts & Casinos", "USD", "0001300514"),
    ("WYNN", "Wynn Resorts Limited", "NASDAQ", "Consumer Cyclical", "Resorts & Casinos", "USD", "0001174922"),
    ("MGM", "MGM Resorts International", "NYSE", "Consumer Cyclical", "Resorts & Casinos", "USD", "0000789570"),
    ("PHM", "PulteGroup Inc.", "NYSE", "Consumer Cyclical", "Residential Construction", "USD", "0000822416"),
    ("NVR", "NVR Inc.", "NYSE", "Consumer Cyclical", "Residential Construction", "USD", "0000906163"),
    ("GRMN", "Garmin Ltd.", "NYSE", "Consumer Cyclical", "Consumer Electronics", "USD", "0001121788"),
    ("DECK", "Deckers Outdoor Corporation", "NYSE", "Consumer Cyclical", "Footwear & Accessories", "USD", "0000910521"),
    ("ETSY", "Etsy Inc.", "NASDAQ", "Consumer Cyclical", "Internet Retail", "USD", "0001370637"),
    ("RCL", "Royal Caribbean Cruises Ltd.", "NYSE", "Consumer Cyclical", "Travel Services", "USD", "0000884887"),
    ("CCL", "Carnival Corporation", "NYSE", "Consumer Cyclical", "Travel Services", "USD", "0000815097"),
    ("EXPE", "Expedia Group Inc.", "NASDAQ", "Consumer Cyclical", "Travel Services", "USD", "0001324424"),
    ("LKQ", "LKQ Corporation", "NASDAQ", "Consumer Cyclical", "Auto Parts", "USD", "0001065696"),
    ("TSCO", "Tractor Supply Company", "NASDAQ", "Consumer Cyclical", "Specialty Retail", "USD", "0000916365"),
    ("DRI", "Darden Restaurants Inc.", "NYSE", "Consumer Cyclical", "Restaurants", "USD", "0000940944"),
    ("CZRS", "Caesars Entertainment Inc.", "NASDAQ", "Consumer Cyclical", "Resorts & Casinos", "USD", "0001590895"),

    # ======================== S&P 500 — CONSUMER STAPLES ========================
    ("WMT", "Walmart Inc.", "NYSE", "Consumer Defensive", "Discount Stores", "USD", "0000104169"),
    ("PG", "Procter & Gamble Company", "NYSE", "Consumer Defensive", "Household & Personal Products", "USD", "0000080424"),
    ("KO", "Coca-Cola Company", "NYSE", "Consumer Defensive", "Beverages - Non-Alcoholic", "USD", "0000021344"),
    ("PEP", "PepsiCo Inc.", "NYSE", "Consumer Defensive", "Beverages - Non-Alcoholic", "USD", "0000077476"),
    ("COST", "Costco Wholesale Corporation", "NASDAQ", "Consumer Defensive", "Discount Stores", "USD", "0000909832"),
    ("PM", "Philip Morris International Inc.", "NYSE", "Consumer Defensive", "Tobacco", "USD", "0001413329"),
    ("MO", "Altria Group Inc.", "NYSE", "Consumer Defensive", "Tobacco", "USD", "0000764180"),
    ("MDLZ", "Mondelez International Inc.", "NASDAQ", "Consumer Defensive", "Confectioners", "USD", "0001103982"),
    ("CL", "Colgate-Palmolive Company", "NYSE", "Consumer Defensive", "Household & Personal Products", "USD", "0000021665"),
    ("KMB", "Kimberly-Clark Corporation", "NYSE", "Consumer Defensive", "Household & Personal Products", "USD", "0000055785"),
    ("GIS", "General Mills Inc.", "NYSE", "Consumer Defensive", "Packaged Foods", "USD", "0000040704"),
    ("K", "Kellanova", "NYSE", "Consumer Defensive", "Packaged Foods", "USD", "0000055067"),
    ("STZ", "Constellation Brands Inc.", "NYSE", "Consumer Defensive", "Beverages - Alcoholic", "USD", "0000016918"),
    ("SYY", "Sysco Corporation", "NYSE", "Consumer Defensive", "Food Distribution", "USD", "0000823313"),
    ("ADM", "Archer-Daniels-Midland Company", "NYSE", "Consumer Defensive", "Farm Products", "USD", "0000007084"),
    ("HSY", "Hershey Company", "NYSE", "Consumer Defensive", "Confectioners", "USD", "0000047111"),
    ("MKC", "McCormick & Company Inc.", "NYSE", "Consumer Defensive", "Packaged Foods", "USD", "0000063754"),
    ("KHC", "Kraft Heinz Company", "NASDAQ", "Consumer Defensive", "Packaged Foods", "USD", "0001637459"),
    ("KR", "Kroger Co.", "NYSE", "Consumer Defensive", "Grocery Stores", "USD", "0000056873"),
    ("WBA", "Walgreens Boots Alliance", "NASDAQ", "Consumer Defensive", "Pharmaceutical Retailers", "USD", "0001618921"),
    ("EL", "Estee Lauder Companies Inc.", "NYSE", "Consumer Defensive", "Household & Personal Products", "USD", "0001001250"),
    ("CHD", "Church & Dwight Co. Inc.", "NYSE", "Consumer Defensive", "Household & Personal Products", "USD", "0000313927"),
    ("CLX", "Clorox Company", "NYSE", "Consumer Defensive", "Household & Personal Products", "USD", "0000021076"),
    ("SJM", "J.M. Smucker Company", "NYSE", "Consumer Defensive", "Packaged Foods", "USD", "0000091419"),
    ("TAP", "Molson Coors Beverage Company", "NYSE", "Consumer Defensive", "Beverages - Alcoholic", "USD", "0000024545"),
    ("CPB", "Campbell Soup Company", "NYSE", "Consumer Defensive", "Packaged Foods", "USD", "0000016732"),
    ("CAG", "Conagra Brands Inc.", "NYSE", "Consumer Defensive", "Packaged Foods", "USD", "0000023217"),
    ("HRL", "Hormel Foods Corporation", "NYSE", "Consumer Defensive", "Packaged Foods", "USD", "0000048465"),
    ("BG", "Bunge Global SA", "NYSE", "Consumer Defensive", "Farm Products", "USD", "0001144519"),
    ("TGT", "Target Corporation", "NYSE", "Consumer Defensive", "Discount Stores", "USD", "0000027419"),
    ("DG", "Dollar General Corporation", "NYSE", "Consumer Defensive", "Discount Stores", "USD", "0000034408"),
    ("DLTR", "Dollar Tree Inc.", "NASDAQ", "Consumer Defensive", "Discount Stores", "USD", "0000935703"),
    ("MNST", "Monster Beverage Corporation", "NASDAQ", "Consumer Defensive", "Beverages - Non-Alcoholic", "USD", "0000865752"),
    ("KVUE", "Kenvue Inc.", "NYSE", "Consumer Defensive", "Household & Personal Products", "USD", "0001944048"),
    ("LW", "Lamb Weston Holdings Inc.", "NYSE", "Consumer Defensive", "Packaged Foods", "USD", "0001679273"),

    # ======================== S&P 500 — INDUSTRIALS ========================
    ("CAT", "Caterpillar Inc.", "NYSE", "Industrials", "Farm & Heavy Construction Machinery", "USD", "0000018230"),
    ("GE", "GE Aerospace", "NYSE", "Industrials", "Aerospace & Defense", "USD", "0000040554"),
    ("UNP", "Union Pacific Corporation", "NYSE", "Industrials", "Railroads", "USD", "0000100885"),
    ("HON", "Honeywell International Inc.", "NASDAQ", "Industrials", "Conglomerates", "USD", "0000773840"),
    ("UPS", "United Parcel Service Inc.", "NYSE", "Industrials", "Integrated Freight & Logistics", "USD", "0001090727"),
    ("RTX", "RTX Corporation", "NYSE", "Industrials", "Aerospace & Defense", "USD", "0000101829"),
    ("LMT", "Lockheed Martin Corporation", "NYSE", "Industrials", "Aerospace & Defense", "USD", "0000936468"),
    ("BA", "Boeing Company", "NYSE", "Industrials", "Aerospace & Defense", "USD", "0000012927"),
    ("DE", "Deere & Company", "NYSE", "Industrials", "Farm & Heavy Construction Machinery", "USD", "0000315189"),
    ("FDX", "FedEx Corporation", "NYSE", "Industrials", "Integrated Freight & Logistics", "USD", "0001048911"),
    ("WM", "Waste Management Inc.", "NYSE", "Industrials", "Waste Management", "USD", "0000823768"),
    ("EMR", "Emerson Electric Co.", "NYSE", "Industrials", "Specialty Industrial Machinery", "USD", "0000032604"),
    ("ETN", "Eaton Corporation plc", "NYSE", "Industrials", "Specialty Industrial Machinery", "USD", "0001551182"),
    ("NOC", "Northrop Grumman Corporation", "NYSE", "Industrials", "Aerospace & Defense", "USD", "0001133421"),
    ("GD", "General Dynamics Corporation", "NYSE", "Industrials", "Aerospace & Defense", "USD", "0000040533"),
    ("CSX", "CSX Corporation", "NASDAQ", "Industrials", "Railroads", "USD", "0000277948"),
    ("NSC", "Norfolk Southern Corporation", "NYSE", "Industrials", "Railroads", "USD", "0000073309"),
    ("ITW", "Illinois Tool Works Inc.", "NYSE", "Industrials", "Specialty Industrial Machinery", "USD", "0000049826"),
    ("MMM", "3M Company", "NYSE", "Industrials", "Conglomerates", "USD", "0000066740"),
    ("GEV", "GE Vernova Inc.", "NYSE", "Industrials", "Specialty Industrial Machinery", "USD", "0001974443"),
    ("TT", "Trane Technologies plc", "NYSE", "Industrials", "Building Products & Equipment", "USD", "0001466258"),
    ("CARR", "Carrier Global Corporation", "NYSE", "Industrials", "Building Products & Equipment", "USD", "0001783180"),
    ("CTAS", "Cintas Corporation", "NASDAQ", "Industrials", "Specialty Business Services", "USD", "0000723254"),
    ("RSG", "Republic Services Inc.", "NYSE", "Industrials", "Waste Management", "USD", "0001060391"),
    ("AME", "AMETEK Inc.", "NYSE", "Industrials", "Specialty Industrial Machinery", "USD", "0000014693"),
    ("FAST", "Fastenal Company", "NASDAQ", "Industrials", "Industrial Distribution", "USD", "0000815556"),
    ("VRSK", "Verisk Analytics Inc.", "NASDAQ", "Industrials", "Consulting Services", "USD", "0001442145"),
    ("IR", "Ingersoll Rand Inc.", "NYSE", "Industrials", "Specialty Industrial Machinery", "USD", "0001699150"),
    ("PWR", "Quanta Services Inc.", "NYSE", "Industrials", "Engineering & Construction", "USD", "0001060714"),
    ("LHX", "L3Harris Technologies Inc.", "NYSE", "Industrials", "Aerospace & Defense", "USD", "0000202058"),
    ("WAB", "Westinghouse Air Brake Technologies", "NYSE", "Industrials", "Railroads", "USD", "0000943452"),
    ("GWW", "W.W. Grainger Inc.", "NYSE", "Industrials", "Industrial Distribution", "USD", "0000076282"),
    ("PCAR", "PACCAR Inc.", "NASDAQ", "Industrials", "Farm & Heavy Construction Machinery", "USD", "0000075362"),
    ("ROK", "Rockwell Automation Inc.", "NYSE", "Industrials", "Specialty Industrial Machinery", "USD", "0001024478"),
    ("OTIS", "Otis Worldwide Corporation", "NYSE", "Industrials", "Specialty Industrial Machinery", "USD", "0001781335"),
    ("DOV", "Dover Corporation", "NYSE", "Industrials", "Specialty Industrial Machinery", "USD", "0000029905"),
    ("CPRT", "Copart Inc.", "NASDAQ", "Industrials", "Specialty Business Services", "USD", "0000900075"),
    ("HWM", "Howmet Aerospace Inc.", "NYSE", "Industrials", "Aerospace & Defense", "USD", "0000004281"),
    ("XYL", "Xylem Inc.", "NYSE", "Industrials", "Specialty Industrial Machinery", "USD", "0001524472"),
    ("AXON", "Axon Enterprise Inc.", "NASDAQ", "Industrials", "Aerospace & Defense", "USD", "0001069183"),
    ("HUBB", "Hubbell Incorporated", "NYSE", "Industrials", "Electrical Equipment & Parts", "USD", "0000048898"),
    ("J", "Jacobs Solutions Inc.", "NYSE", "Industrials", "Engineering & Construction", "USD", "0000049196"),
    ("EFX", "Equifax Inc.", "NYSE", "Industrials", "Consulting Services", "USD", "0000033185"),
    ("SWK", "Stanley Black & Decker Inc.", "NYSE", "Industrials", "Tools & Accessories", "USD", "0000093556"),
    ("DAL", "Delta Air Lines Inc.", "NYSE", "Industrials", "Airlines", "USD", "0000027904"),
    ("UAL", "United Airlines Holdings Inc.", "NASDAQ", "Industrials", "Airlines", "USD", "0000100517"),
    ("LUV", "Southwest Airlines Co.", "NYSE", "Industrials", "Airlines", "USD", "0000092380"),
    ("TDG", "TransDigm Group Incorporated", "NYSE", "Industrials", "Aerospace & Defense", "USD", "0001260221"),
    ("IEX", "IDEX Corporation", "NYSE", "Industrials", "Specialty Industrial Machinery", "USD", "0000832101"),
    ("NDSN", "Nordson Corporation", "NASDAQ", "Industrials", "Specialty Industrial Machinery", "USD", "0000072331"),

    # ======================== S&P 500 — ENERGY ========================
    ("XOM", "Exxon Mobil Corporation", "NYSE", "Energy", "Oil & Gas Integrated", "USD", "0000034088"),
    ("CVX", "Chevron Corporation", "NYSE", "Energy", "Oil & Gas Integrated", "USD", "0000093410"),
    ("COP", "ConocoPhillips", "NYSE", "Energy", "Oil & Gas Exploration & Production", "USD", "0001163165"),
    ("SLB", "Schlumberger Limited", "NYSE", "Energy", "Oil & Gas Equipment & Services", "USD", "0000087347"),
    ("EOG", "EOG Resources Inc.", "NYSE", "Energy", "Oil & Gas Exploration & Production", "USD", "0000821189"),
    ("MPC", "Marathon Petroleum Corporation", "NYSE", "Energy", "Oil & Gas Refining & Marketing", "USD", "0001510295"),
    ("VLO", "Valero Energy Corporation", "NYSE", "Energy", "Oil & Gas Refining & Marketing", "USD", "0001035002"),
    ("PSX", "Phillips 66", "NYSE", "Energy", "Oil & Gas Refining & Marketing", "USD", "0001534701"),
    ("PXD", "Pioneer Natural Resources", "NYSE", "Energy", "Oil & Gas Exploration & Production", "USD", "0001038357"),
    ("WMB", "Williams Companies Inc.", "NYSE", "Energy", "Oil & Gas Midstream", "USD", "0000107263"),
    ("OKE", "ONEOK Inc.", "NYSE", "Energy", "Oil & Gas Midstream", "USD", "0001039684"),
    ("KMI", "Kinder Morgan Inc.", "NYSE", "Energy", "Oil & Gas Midstream", "USD", "0001110805"),
    ("HES", "Hess Corporation", "NYSE", "Energy", "Oil & Gas Exploration & Production", "USD", "0000004447"),
    ("DVN", "Devon Energy Corporation", "NYSE", "Energy", "Oil & Gas Exploration & Production", "USD", "0001090012"),
    ("FANG", "Diamondback Energy Inc.", "NASDAQ", "Energy", "Oil & Gas Exploration & Production", "USD", "0001539838"),
    ("BKR", "Baker Hughes Company", "NASDAQ", "Energy", "Oil & Gas Equipment & Services", "USD", "0001701605"),
    ("HAL", "Halliburton Company", "NYSE", "Energy", "Oil & Gas Equipment & Services", "USD", "0000045012"),
    ("TRGP", "Targa Resources Corp.", "NYSE", "Energy", "Oil & Gas Midstream", "USD", "0001423689"),
    ("CTRA", "Coterra Energy Inc.", "NYSE", "Energy", "Oil & Gas Exploration & Production", "USD", "0000858470"),
    ("OXY", "Occidental Petroleum Corporation", "NYSE", "Energy", "Oil & Gas Exploration & Production", "USD", "0000797468"),
    ("EQT", "EQT Corporation", "NYSE", "Energy", "Oil & Gas Exploration & Production", "USD", "0000033213"),
    ("MRO", "Marathon Oil Corporation", "NYSE", "Energy", "Oil & Gas Exploration & Production", "USD", "0000101778"),
    ("APA", "APA Corporation", "NASDAQ", "Energy", "Oil & Gas Exploration & Production", "USD", "0000006769"),

    # ======================== S&P 500 — COMMUNICATION SERVICES ========================
    ("DIS", "Walt Disney Company", "NYSE", "Communication Services", "Entertainment", "USD", "0001744489"),
    ("NFLX", "Netflix Inc.", "NASDAQ", "Communication Services", "Entertainment", "USD", "0001065280"),
    ("CMCSA", "Comcast Corporation", "NASDAQ", "Communication Services", "Telecom Services", "USD", "0001166691"),
    ("VZ", "Verizon Communications Inc.", "NYSE", "Communication Services", "Telecom Services", "USD", "0000732712"),
    ("T", "AT&T Inc.", "NYSE", "Communication Services", "Telecom Services", "USD", "0000732717"),
    ("TMUS", "T-Mobile US Inc.", "NASDAQ", "Communication Services", "Telecom Services", "USD", "0001283699"),
    ("CHTR", "Charter Communications Inc.", "NASDAQ", "Communication Services", "Entertainment", "USD", "0001091667"),
    ("EA", "Electronic Arts Inc.", "NASDAQ", "Communication Services", "Electronic Gaming & Multimedia", "USD", "0000712515"),
    ("WBD", "Warner Bros. Discovery Inc.", "NASDAQ", "Communication Services", "Entertainment", "USD", "0001437107"),
    ("TTWO", "Take-Two Interactive Software", "NASDAQ", "Communication Services", "Electronic Gaming & Multimedia", "USD", "0000946581"),
    ("LYV", "Live Nation Entertainment Inc.", "NYSE", "Communication Services", "Entertainment", "USD", "0001335258"),
    ("MTCH", "Match Group Inc.", "NASDAQ", "Communication Services", "Internet Content & Information", "USD", "0001575515"),
    ("PARA", "Paramount Global", "NASDAQ", "Communication Services", "Entertainment", "USD", "0000813828"),
    ("FOX", "Fox Corporation Class B", "NASDAQ", "Communication Services", "Entertainment", "USD", "0001754301"),
    ("FOXA", "Fox Corporation Class A", "NASDAQ", "Communication Services", "Entertainment", "USD", "0001754301"),
    ("OMC", "Omnicom Group Inc.", "NYSE", "Communication Services", "Advertising Agencies", "USD", "0000029989"),
    ("IPG", "Interpublic Group of Companies", "NYSE", "Communication Services", "Advertising Agencies", "USD", "0000051644"),
    ("NWSA", "News Corp Class A", "NASDAQ", "Communication Services", "Publishing", "USD", "0001564708"),

    # ======================== S&P 500 — REAL ESTATE ========================
    ("AMT", "American Tower Corporation", "NYSE", "Real Estate", "REIT - Specialty", "USD", "0001053507"),
    ("PLD", "Prologis Inc.", "NYSE", "Real Estate", "REIT - Industrial", "USD", "0001045609"),
    ("CCI", "Crown Castle Inc.", "NYSE", "Real Estate", "REIT - Specialty", "USD", "0001051470"),
    ("EQIX", "Equinix Inc.", "NASDAQ", "Real Estate", "REIT - Specialty", "USD", "0001101239"),
    ("SPG", "Simon Property Group Inc.", "NYSE", "Real Estate", "REIT - Retail", "USD", "0001063761"),
    ("O", "Realty Income Corporation", "NYSE", "Real Estate", "REIT - Retail", "USD", "0000726728"),
    ("PSA", "Public Storage", "NYSE", "Real Estate", "REIT - Specialty", "USD", "0000077890"),
    ("DLR", "Digital Realty Trust Inc.", "NYSE", "Real Estate", "REIT - Specialty", "USD", "0001365135"),
    ("WELL", "Welltower Inc.", "NYSE", "Real Estate", "REIT - Healthcare Facilities", "USD", "0000766704"),
    ("VICI", "VICI Properties Inc.", "NYSE", "Real Estate", "REIT - Specialty", "USD", "0001705696"),
    ("SBAC", "SBA Communications Corporation", "NASDAQ", "Real Estate", "REIT - Specialty", "USD", "0001034054"),
    ("AVB", "AvalonBay Communities Inc.", "NYSE", "Real Estate", "REIT - Residential", "USD", "0000915912"),
    ("EQR", "Equity Residential", "NYSE", "Real Estate", "REIT - Residential", "USD", "0000906107"),
    ("ARE", "Alexandria Real Estate Equities", "NYSE", "Real Estate", "REIT - Office", "USD", "0001000004"),
    ("MAA", "Mid-America Apartment Communities", "NYSE", "Real Estate", "REIT - Residential", "USD", "0000036519"),
    ("IRM", "Iron Mountain Incorporated", "NYSE", "Real Estate", "REIT - Specialty", "USD", "0001020569"),
    ("ESS", "Essex Property Trust Inc.", "NYSE", "Real Estate", "REIT - Residential", "USD", "0000920522"),
    ("INVH", "Invitation Homes Inc.", "NYSE", "Real Estate", "REIT - Residential", "USD", "0001687229"),
    ("KIM", "Kimco Realty Corporation", "NYSE", "Real Estate", "REIT - Retail", "USD", "0000879101"),
    ("REG", "Regency Centers Corporation", "NASDAQ", "Real Estate", "REIT - Retail", "USD", "0000910606"),
    ("HST", "Host Hotels & Resorts Inc.", "NASDAQ", "Real Estate", "REIT - Hotel & Motel", "USD", "0001061937"),
    ("CPT", "Camden Property Trust", "NYSE", "Real Estate", "REIT - Residential", "USD", "0000906163"),
    ("UDR", "UDR Inc.", "NYSE", "Real Estate", "REIT - Residential", "USD", "0000074260"),
    ("BXP", "BXP Inc.", "NYSE", "Real Estate", "REIT - Office", "USD", "0001037540"),

    # ======================== S&P 500 — UTILITIES ========================
    ("NEE", "NextEra Energy Inc.", "NYSE", "Utilities", "Utilities - Regulated Electric", "USD", "0000753308"),
    ("DUK", "Duke Energy Corporation", "NYSE", "Utilities", "Utilities - Regulated Electric", "USD", "0001326160"),
    ("SO", "Southern Company", "NYSE", "Utilities", "Utilities - Regulated Electric", "USD", "0000092122"),
    ("D", "Dominion Energy Inc.", "NYSE", "Utilities", "Utilities - Regulated Electric", "USD", "0000715957"),
    ("AEP", "American Electric Power Company", "NASDAQ", "Utilities", "Utilities - Regulated Electric", "USD", "0000004904"),
    ("EXC", "Exelon Corporation", "NASDAQ", "Utilities", "Utilities - Regulated Electric", "USD", "0001109357"),
    ("SRE", "Sempra", "NYSE", "Utilities", "Utilities - Diversified", "USD", "0001032208"),
    ("WEC", "WEC Energy Group Inc.", "NYSE", "Utilities", "Utilities - Regulated Electric", "USD", "0000783325"),
    ("ED", "Consolidated Edison Inc.", "NYSE", "Utilities", "Utilities - Regulated Electric", "USD", "0001047862"),
    ("PCG", "PG&E Corporation", "NYSE", "Utilities", "Utilities - Regulated Electric", "USD", "0001004980"),
    ("XEL", "Xcel Energy Inc.", "NASDAQ", "Utilities", "Utilities - Regulated Electric", "USD", "0000072903"),
    ("ES", "Eversource Energy", "NYSE", "Utilities", "Utilities - Regulated Electric", "USD", "0000072741"),
    ("AWK", "American Water Works Company", "NYSE", "Utilities", "Utilities - Regulated Water", "USD", "0001410636"),
    ("EIX", "Edison International", "NYSE", "Utilities", "Utilities - Regulated Electric", "USD", "0000827052"),
    ("ETR", "Entergy Corporation", "NYSE", "Utilities", "Utilities - Regulated Electric", "USD", "0000065984"),
    ("DTE", "DTE Energy Company", "NYSE", "Utilities", "Utilities - Regulated Electric", "USD", "0000936340"),
    ("FE", "FirstEnergy Corp.", "NYSE", "Utilities", "Utilities - Regulated Electric", "USD", "0001031296"),
    ("PPL", "PPL Corporation", "NYSE", "Utilities", "Utilities - Regulated Electric", "USD", "0000922224"),
    ("CMS", "CMS Energy Corporation", "NYSE", "Utilities", "Utilities - Regulated Electric", "USD", "0000811156"),
    ("ATO", "Atmos Energy Corporation", "NYSE", "Utilities", "Utilities - Regulated Gas", "USD", "0000731802"),
    ("LNT", "Alliant Energy Corporation", "NASDAQ", "Utilities", "Utilities - Regulated Electric", "USD", "0000352541"),
    ("AES", "AES Corporation", "NYSE", "Utilities", "Utilities - Diversified", "USD", "0000874761"),
    ("CNP", "CenterPoint Energy Inc.", "NYSE", "Utilities", "Utilities - Regulated Electric", "USD", "0001130310"),
    ("PNW", "Pinnacle West Capital", "NYSE", "Utilities", "Utilities - Regulated Electric", "USD", "0000764622"),
    ("NI", "NiSource Inc.", "NYSE", "Utilities", "Utilities - Regulated Gas", "USD", "0001111711"),
    ("EVRG", "Evergy Inc.", "NYSE", "Utilities", "Utilities - Regulated Electric", "USD", "0001711269"),

    # ======================== S&P 500 — MATERIALS ========================
    ("LIN", "Linde plc", "NYSE", "Materials", "Specialty Chemicals", "USD", "0001707925"),
    ("APD", "Air Products and Chemicals Inc.", "NYSE", "Materials", "Specialty Chemicals", "USD", "0000002969"),
    ("ECL", "Ecolab Inc.", "NYSE", "Materials", "Specialty Chemicals", "USD", "0000031462"),
    ("SHW", "Sherwin-Williams Company", "NYSE", "Materials", "Specialty Chemicals", "USD", "0000089800"),
    ("FCX", "Freeport-McMoRan Inc.", "NYSE", "Materials", "Copper", "USD", "0000831259"),
    ("NEM", "Newmont Corporation", "NYSE", "Materials", "Gold", "USD", "0001164727"),
    ("NUE", "Nucor Corporation", "NYSE", "Materials", "Steel", "USD", "0000073309"),
    ("VMC", "Vulcan Materials Company", "NYSE", "Materials", "Building Materials", "USD", "0001396009"),
    ("MLM", "Martin Marietta Materials Inc.", "NYSE", "Materials", "Building Materials", "USD", "0000916076"),
    ("PPG", "PPG Industries Inc.", "NYSE", "Materials", "Specialty Chemicals", "USD", "0000079879"),
    ("DD", "DuPont de Nemours Inc.", "NYSE", "Materials", "Specialty Chemicals", "USD", "0001666700"),
    ("DOW", "Dow Inc.", "NYSE", "Materials", "Chemicals", "USD", "0001751788"),
    ("EMN", "Eastman Chemical Company", "NYSE", "Materials", "Specialty Chemicals", "USD", "0000915389"),
    ("ALB", "Albemarle Corporation", "NYSE", "Materials", "Specialty Chemicals", "USD", "0000915389"),
    ("CE", "Celanese Corporation", "NYSE", "Materials", "Chemicals", "USD", "0001306830"),
    ("IFF", "International Flavors & Fragrances", "NYSE", "Materials", "Specialty Chemicals", "USD", "0000051253"),
    ("CF", "CF Industries Holdings Inc.", "NYSE", "Materials", "Agricultural Inputs", "USD", "0001324404"),
    ("MOS", "Mosaic Company", "NYSE", "Materials", "Agricultural Inputs", "USD", "0001285785"),
    ("STLD", "Steel Dynamics Inc.", "NASDAQ", "Materials", "Steel", "USD", "0001022671"),
    ("PKG", "Packaging Corporation of America", "NYSE", "Materials", "Packaging & Containers", "USD", "0000075473"),
    ("IP", "International Paper Company", "NYSE", "Materials", "Packaging & Containers", "USD", "0000049826"),
    ("AVY", "Avery Dennison Corporation", "NYSE", "Materials", "Packaging & Containers", "USD", "0000008818"),
    ("BALL", "Ball Corporation", "NYSE", "Materials", "Packaging & Containers", "USD", "0000009389"),
    ("FMC", "FMC Corporation", "NYSE", "Materials", "Agricultural Inputs", "USD", "0000037996"),
    ("AMCR", "Amcor plc", "NYSE", "Materials", "Packaging & Containers", "USD", "0001748790"),
    ("RPM", "RPM International Inc.", "NYSE", "Materials", "Specialty Chemicals", "USD", "0000081461"),

    # ======================== TSX 60 — CANADIAN COMPANIES ========================
    # Banks (with US CIKs for cross-listed companies)
    ("RY", "Royal Bank of Canada", "TSX", "Financials", "Banks - Diversified", "CAD", "0001000275"),
    ("TD", "Toronto-Dominion Bank", "TSX", "Financials", "Banks - Diversified", "CAD", "0000947263"),
    ("BNS", "Bank of Nova Scotia", "TSX", "Financials", "Banks - Diversified", "CAD", "0001000228"),
    ("BMO", "Bank of Montreal", "TSX", "Financials", "Banks - Diversified", "CAD", "0000927971"),
    ("CM", "Canadian Imperial Bank of Commerce", "TSX", "Financials", "Banks - Diversified", "CAD", "0001045520"),
    ("NA", "National Bank of Canada", "TSX", "Financials", "Banks - Diversified", "CAD", None),
    ("MFC", "Manulife Financial Corporation", "TSX", "Financials", "Insurance - Life", "CAD", "0001086888"),
    ("SLF", "Sun Life Financial Inc.", "TSX", "Financials", "Insurance - Life", "CAD", "0001021102"),
    ("IFC", "Intact Financial Corporation", "TSX", "Financials", "Insurance - Property & Casualty", "CAD", None),
    ("GWO", "Great-West Lifeco Inc.", "TSX", "Financials", "Insurance - Life", "CAD", None),
    ("POW", "Power Corporation of Canada", "TSX", "Financials", "Insurance - Diversified", "CAD", None),
    ("X", "TMX Group Limited", "TSX", "Financials", "Financial Data & Exchanges", "CAD", None),

    # Energy (with US CIKs for cross-listed)
    ("ENB", "Enbridge Inc.", "TSX", "Energy", "Oil & Gas Midstream", "CAD", "0000895728"),
    ("TRP", "TC Energy Corporation", "TSX", "Energy", "Oil & Gas Midstream", "CAD", "0001071804"),
    ("CNQ", "Canadian Natural Resources", "TSX", "Energy", "Oil & Gas Exploration & Production", "CAD", "0001017413"),
    ("SU", "Suncor Energy Inc.", "TSX", "Energy", "Oil & Gas Integrated", "CAD", "0001101169"),
    ("IMO", "Imperial Oil Limited", "TSX", "Energy", "Oil & Gas Integrated", "CAD", "0000049938"),
    ("CVE", "Cenovus Energy Inc.", "TSX", "Energy", "Oil & Gas Integrated", "CAD", "0001225026"),
    ("TOU", "Tourmaline Oil Corp.", "TSX", "Energy", "Oil & Gas Exploration & Production", "CAD", None),
    ("ARX", "ARC Resources Ltd.", "TSX", "Energy", "Oil & Gas Exploration & Production", "CAD", None),
    ("PPL.TO", "Pembina Pipeline Corporation", "TSX", "Energy", "Oil & Gas Midstream", "CAD", "0001173489"),
    ("KEL", "Keyera Corp.", "TSX", "Energy", "Oil & Gas Midstream", "CAD", None),

    # Industrials (with US CIKs for cross-listed)
    ("CNR", "Canadian National Railway", "TSX", "Industrials", "Railroads", "CAD", "0001001085"),
    ("CP", "Canadian Pacific Kansas City", "TSX", "Industrials", "Railroads", "CAD", "0001001063"),
    ("AC", "Air Canada", "TSX", "Industrials", "Airlines", "CAD", None),
    ("TFI", "TFI International Inc.", "TSX", "Industrials", "Integrated Freight & Logistics", "CAD", "0001750043"),
    ("WCN", "Waste Connections Inc.", "TSX", "Industrials", "Waste Management", "CAD", "0001057058"),
    ("RBA", "RB Global Inc.", "TSX", "Industrials", "Specialty Business Services", "CAD", "0001046102"),
    ("CAE", "CAE Inc.", "TSX", "Industrials", "Aerospace & Defense", "CAD", "0000885462"),
    ("STN", "Stantec Inc.", "TSX", "Industrials", "Engineering & Construction", "CAD", None),

    # Technology (with US CIKs for cross-listed)
    ("SHOP", "Shopify Inc.", "TSX", "Technology", "Software - Application", "CAD", "0001594805"),
    ("CSU", "Constellation Software Inc.", "TSX", "Technology", "Software - Application", "CAD", None),
    ("CGI", "CGI Inc.", "TSX", "Technology", "Information Technology Services", "CAD", "0001124610"),
    ("OTEX", "Open Text Corporation", "TSX", "Technology", "Software - Application", "CAD", "0001002638"),
    ("DCBO", "Docebo Inc.", "TSX", "Technology", "Software - Application", "CAD", None),
    ("LSPD", "Lightspeed Commerce Inc.", "TSX", "Technology", "Software - Application", "CAD", None),
    ("KXS", "Kinaxis Inc.", "TSX", "Technology", "Software - Application", "CAD", None),

    # Materials (with US CIKs for cross-listed)
    ("ABX", "Barrick Gold Corporation", "TSX", "Materials", "Gold", "CAD", "0000756894"),
    ("NTR", "Nutrien Ltd.", "TSX", "Materials", "Agricultural Inputs", "CAD", "0001725964"),
    ("FNV", "Franco-Nevada Corporation", "TSX", "Materials", "Gold", "CAD", "0001456233"),
    ("WPM", "Wheaton Precious Metals Corp.", "TSX", "Materials", "Gold", "CAD", "0001494728"),
    ("FM", "First Quantum Minerals", "TSX", "Materials", "Copper", "CAD", None),
    ("AEM", "Agnico Eagle Mines Limited", "TSX", "Materials", "Gold", "CAD", "0000002809"),
    ("CCL.B", "CCL Industries Inc.", "TSX", "Materials", "Packaging & Containers", "CAD", None),
    ("TFII", "Teck Resources Limited", "TSX", "Materials", "Other Industrial Metals", "CAD", "0000070318"),

    # Utilities
    ("FTS", "Fortis Inc.", "TSX", "Utilities", "Utilities - Regulated Electric", "CAD", "0001574263"),
    ("EMA", "Emera Incorporated", "TSX", "Utilities", "Utilities - Regulated Electric", "CAD", None),
    ("H", "Hydro One Limited", "TSX", "Utilities", "Utilities - Regulated Electric", "CAD", None),
    ("AQN", "Algonquin Power & Utilities", "TSX", "Utilities", "Utilities - Diversified", "CAD", "0001174169"),
    ("CU", "Canadian Utilities Limited", "TSX", "Utilities", "Utilities - Regulated Electric", "CAD", None),
    ("BEP.UN", "Brookfield Renewable Partners", "TSX", "Utilities", "Utilities - Renewable", "CAD", "0001562476"),

    # Consumer
    ("ATD", "Alimentation Couche-Tard", "TSX", "Consumer Defensive", "Specialty Retail", "CAD", None),
    ("QSR", "Restaurant Brands International", "TSX", "Consumer Cyclical", "Restaurants", "CAD", "0001618756"),
    ("DOL", "Dollarama Inc.", "TSX", "Consumer Defensive", "Discount Stores", "CAD", None),
    ("MRU", "Metro Inc.", "TSX", "Consumer Defensive", "Grocery Stores", "CAD", None),
    ("SAP.TO", "Saputo Inc.", "TSX", "Consumer Defensive", "Packaged Foods", "CAD", None),
    ("GIL", "Gildan Activewear Inc.", "TSX", "Consumer Cyclical", "Apparel Manufacturing", "CAD", "0001060349"),
    ("WFG", "West Fraser Timber Co. Ltd.", "TSX", "Consumer Cyclical", "Lumber & Wood Production", "CAD", None),

    # Telecom
    ("BCE", "BCE Inc.", "TSX", "Communication Services", "Telecom Services", "CAD", "0000718940"),
    ("T.TO", "TELUS Corporation", "TSX", "Communication Services", "Telecom Services", "CAD", "0001094530"),
    ("RCI.B", "Rogers Communications Inc.", "TSX", "Communication Services", "Telecom Services", "CAD", "0000775105"),
    ("QBR.B", "Quebecor Inc.", "TSX", "Communication Services", "Telecom Services", "CAD", None),

    # Real Estate
    ("BAM", "Brookfield Asset Management", "TSX", "Real Estate", "Asset Management", "CAD", "0001001085"),
    ("BN", "Brookfield Corporation", "TSX", "Real Estate", "Asset Management", "CAD", "0001001085"),
    ("CAR.UN", "Canadian Apartment Properties REIT", "TSX", "Real Estate", "REIT - Residential", "CAD", None),
    ("REI.UN", "RioCan REIT", "TSX", "Real Estate", "REIT - Retail", "CAD", None),
    ("AP.UN", "Allied Properties REIT", "TSX", "Real Estate", "REIT - Office", "CAD", None),
    ("GRT.UN", "Granite REIT", "TSX", "Real Estate", "REIT - Industrial", "CAD", None),
]


async def seed():
    async with async_session_factory() as session:
        inserted = 0
        skipped = 0
        for ticker, name, exchange, sector, industry, currency, cik in COMPANIES:
            result = await session.execute(
                text(
                    """
                    INSERT INTO companies (id, ticker, name, exchange, sector, industry, currency, cik, is_active, created_at, updated_at)
                    VALUES (gen_random_uuid(), :ticker, :name, :exchange, :sector, :industry, :currency, :cik, true, now(), now())
                    ON CONFLICT (ticker) DO UPDATE SET
                        name = EXCLUDED.name,
                        exchange = EXCLUDED.exchange,
                        sector = EXCLUDED.sector,
                        industry = EXCLUDED.industry,
                        currency = EXCLUDED.currency,
                        cik = COALESCE(EXCLUDED.cik, companies.cik),
                        updated_at = now()
                    """
                ),
                {
                    "ticker": ticker,
                    "name": name,
                    "exchange": exchange,
                    "sector": sector,
                    "industry": industry,
                    "currency": currency,
                    "cik": cik,
                },
            )
            if result.rowcount > 0:
                inserted += 1
            else:
                skipped += 1
        await session.commit()
    print(f"Seeded {inserted} companies ({skipped} unchanged).")
    print(f"Total in seed list: {len(COMPANIES)}")


if __name__ == "__main__":
    asyncio.run(seed())
