from uuid import UUID

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.thesis_version import ThesisVersion


class ThesisService:
    def __init__(self, db: AsyncSession):
        self.db = db

    async def get_by_id(self, version_id: UUID) -> ThesisVersion | None:
        result = await self.db.execute(
            select(ThesisVersion).where(ThesisVersion.id == version_id)
        )
        return result.scalar_one_or_none()

    async def get_latest(self, company_id: UUID) -> ThesisVersion | None:
        q = (
            select(ThesisVersion)
            .where(ThesisVersion.company_id == company_id)
            .order_by(ThesisVersion.version.desc())
            .limit(1)
        )
        result = await self.db.execute(q)
        return result.scalar_one_or_none()

    async def list_versions(
        self, company_id: UUID, page: int = 1, per_page: int = 10
    ) -> tuple[list[ThesisVersion], int]:
        count_q = select(func.count()).where(ThesisVersion.company_id == company_id)
        total = (await self.db.execute(count_q)).scalar_one()

        q = (
            select(ThesisVersion)
            .where(ThesisVersion.company_id == company_id)
            .order_by(ThesisVersion.version.desc())
            .offset((page - 1) * per_page)
            .limit(per_page)
        )
        result = await self.db.execute(q)
        items = list(result.scalars().all())
        return items, total

    async def create_version(
        self,
        company_id: UUID,
        snapshot_id: UUID,
        thesis_data: dict,
        prior_version: ThesisVersion | None = None,
    ) -> ThesisVersion:
        """Persist a new thesis version generated by the LLM."""
        # Determine next version number
        latest = await self.get_latest(company_id)
        next_version = (latest.version + 1) if latest else 1

        thesis = ThesisVersion(
            company_id=company_id,
            snapshot_id=snapshot_id,
            version=next_version,
            bull_case=thesis_data["bull_case"],
            bull_target=thesis_data.get("bull_target"),
            base_case=thesis_data["base_case"],
            base_target=thesis_data.get("base_target"),
            bear_case=thesis_data["bear_case"],
            bear_target=thesis_data.get("bear_target"),
            key_drivers=thesis_data["key_drivers"],
            key_risks=thesis_data["key_risks"],
            catalysts=thesis_data["catalysts"],
            thesis_integrity_score=thesis_data.get("thesis_integrity_score"),
            integrity_rationale=thesis_data.get("integrity_rationale"),
            prior_version_id=prior_version.id if prior_version else None,
            drift_summary=thesis_data.get("drift_summary"),
            conviction_direction=thesis_data.get("conviction_direction"),
            llm_model_used=thesis_data.get("llm_model_used", "claude-sonnet-4-5-20250929"),
        )
        self.db.add(thesis)
        await self.db.commit()
        return thesis
